### PR TITLE
refactor(parse-all): report error per parser

### PR DESCRIPTION
**Pull request by petergoes**
When a parser errors, report what happend to the user. Continue with all
parsers before exiting. Parsers are started in paralell, we need to wait
for all of them to complete to clean up the temp folder.

### CODE REVIEW

**Comment by petergoes** [comment]
#70

**Comment by jpsc** [comment]
Looks good to me :)

**Comment by jbmoelker** [comment]
as discussed:
- move `process.exitCode = 1;` to `bin/fastatic`
- return `parse` promise after copying to `dest` so that consuming modules (like `bin/fastatic`) can hook onto resolve/reject. and use this `parse` to finish internal cleanup and logging.

**Comment by jbmoelker** [comment]
@petergoes I propose we revisit this one after you've updated the new stats parser. I think the signature of the main `index.js` will have to change to return those stats.

**Comment by petergoes** [comment]
the last commit builds on top of #94

**Comment by petergoes** [comment]
I just realised, by handeling error reporting I do in the last commit, the module is never going to exit with an exit code. Any error in the parsers is caught, so the `catch` wil execute, hence, consuming modules will always have to actively check the output to see if there are errors and can't rely on their own `catch` implementation.

Maybe it's worth to discuss this in person?

**Comment by petergoes** [comment]
Closing this PR and putting the error reporting in another branch based on #94

**Pull request closed without merging**
